# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f9bc1bde32ac32970d65766a55fb2c754d09186e8ea753afb7c3f0f86c2fc5a987e1d931451b7f09f945dc79fbceb511eac822e24f39f8a7ee2e61b01551afa5

test:
  secret_key_base: 732165d3239b8e8e371d2b62282a8b6f12231ecc5afeeccc9a4d75aae067692325f68775fb7837c6433cec6a9aa76d4958dac6f172fdc6165e0bda9efa37b77b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
